const actionTypes = {
  cart: {
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_CART_ITEM: "DELETE_CART_ITEM",
    DELETE_ALL_CART: "DELETE_ALL-CART",
  },

  product: {
    GET_PRODUCT: "GET_PRODUCT",
    DECREASE_PRODUCT_IN_STOCK: "DECREASE_PRODUCT_IN_STOCK",
    INCREASE_PRODUCT_IN_STOCK: "INCREASE_PRODUCT_IN_STOCK",
   
  },
};

export default actionTypes;
